---
services:
  db:
    container_name: db
    image: divyagorantla1708/mynewproject:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 2
      
  auth_service:
    container_name: auth_service
    image: divyagorantla1708/mynewproject:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 2
    depends_on:
      - db
  book_service:
    container_name: book_service
    image: divyagorantla1708/mynewproject:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 2
    depends_on:
      - db
  borrow_service:
    container_name: borrow_service
    image: divyagorantla1708/mynewproject:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    depends_on:
      - db
  frontend:
    container_name: frontend
    image: divyagorantla1708/mynewproject:frontendimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
    depends_on:
      - auth_service
      - book_service
      - borrow_service
